linux_display_server wayland
font_family family="Cascadia Mono NF"
# font_family family="Monaspace Radon NF"
# font_family family="JetBrainsMono Nerd Font"
font_size 11.0
disable_ligatures never
scrollback_lines 10000
confirm_os_window_close 0
window_padding_width 6
background_opacity  0.8
background_blur 1
tab_bar_style fade
tab_fade 1
active_tab_font_style   bold
inactive_tab_font_style bold

include dank-theme.conf
include dank-tabs.conf
include local.conf
