#!/usr/bin/env bash

set -Eeuo pipefail

readonly REPO_NAME="fedora-config"
readonly DOT_DIR="$HOME/.${REPO_NAME}"

log() {
  printf "\033[1;34mℹ\033[0m %s\n" "$*"
}

error() {
  printf "\033[1;31m✖\033[0m %s\n" "$*" >&2
}

die() {
  error "$*"
  exit 1
}

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

pixi_install() {
  has_cmd pixi || {
    has_cmd curl || die "curl is not installed. Quitting."

    log "Installing pixi."
    curl -fsSL https://pixi.sh/install.sh | sh
  }

  has_cmd pixi || die "Failed to install pixi"
  pixi global install nushell
}

fresh_install() {
  [ -d "$DOT_DIR" ] || die "$DOT_DIR does not exist. Quitting."
  pixi_install

  if ! has_cmd nu; then
    log "nu is not installed. Skipping."
    return
  fi

  "$DOT_DIR"/scripts/setup.nu shell || die "shell/fish setup failed"

  echo ""
  log "Shell configuration complete."
  log "Use ~/.fedora-config/scripts/setup.nu for further setup."
  echo ""
}

main() {
  has_cmd dnf || die "Only Fedora is supported. Quitting."
  export PATH="$HOME/.pixi/bin:$PATH"
  fresh_install
}
