#!/usr/bin/env bash

set -Eeuo pipefail

readonly REPO_NAME="fedora-config"
readonly DOT_DIR="$HOME/.${REPO_NAME}"

log() {
  printf "\033[1;34mℹ\033[0m %s\n" "$*"
}

error() {
  printf "\033[1;31m✖\033[0m %s\n" "$*" >&2
}

die() {
  error "$*"
  exit 1
}

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

main() {
  has_cmd zypper || die "Only Tumbleweed is supported. Quitting."
  log "Updating package manager cache..."
  sudo zypper refresh

  has_cmd git || {
    log "Installing git..."
    sudo zypper install -y git
  }

  if [ ! -d "$DOT_DIR" ]; then
    log "Cloning dotfiles repository..."
    git clone https://github.com/pervezfunctor/fedora-config "$DOT_DIR" ||
      die "git clone failed"
  fi

  log "Removing busybox..."
  sudo zypper remove -y busybox* || true
  log "Installing less..."
  sudo zypper install -y less
  log "Installing packages..."
  sudo zypper install -y nushell bat difftastic duf fd gdu gh git \
    htop jq less rclone ripgrep rsync ShellCheck shfmt tar tealdeer \
    tmux trash-cli ugrep unzip yq zstd dysk bottom starship xh fish

  log "Setting up fish shell..."
  mkdir -p ~/.config/fish
  log "Trashing old fish config, restore with 'trash-restore'..."
  if ! trash ~/.config/fish/config.fish; then
    log "$HOME/.config/fish/config.fish does not exist. Skipping trash."
  fi
  log "Linking new fish config..."
  ln -sf "$DOT_DIR"/config.fish ~/.config/fish/config.fish
  log "Setting fish as default shell..."
  if ! chsh -s /usr/bin/fish; then
    log "Failed to set fish as default shell. You may need to run 'sudo chsh -s $(which fish) $USER' manually."
  else
    log "Fish set as default shell successfully."
  fi
}

main
