export DOT_DIR="$HOME/.fgc"
export PATH="$HOME/.local/share/flatpak/exports/bin:$DOT_DIR/scripts:$HOME/.vite-plus/bin:$HOME/bin:$HOME/.pixi/bin:$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

if ! [[ $- == *i* ]]; then
  return
fi

if command -v rpm-ostree >/dev/null 2>&1; then
  return
fi

if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

if command -v starship &>/dev/null; then
  eval "$(starship init bash)"
fi
